---
title: "aldex2"
output: html_document
date: "2024-06-03"
---

- Load data and packages and format

```{r}
library(tidyverse)
library(qiime2R)
library(ComplexHeatmap)
library(circlize)
library(viridis)
library(ggh4x)

tab <- read_qza("../Data/table_SMOQ_filt.qza")$data %>% as.data.frame() %>% 
rownames_to_column(var = "Feature.ID") 
taxa<- qiime2R::read_qza("../Data/taxonomy_SMOQ_ver10.qza")$data %>% as.data.frame()
metadata<- read.delim("../Data/its_map.txt")

tab_tax<- tab %>% inner_join(taxa)

tab_taxa<- tab_tax %>% dplyr::select(OTUID=Feature.ID, `121D`:`221D`, taxonomy=Taxon)

vector_order<- c("111D" , "112D", "113D" ,"121D", "122D" ,"123D", "111R" ,"112R", "113R", "121R", "122R" ,"123R",
                 "211D" ,"212D" ,"213D" ,"221D" ,"222D" ,"223D", "211R" ,"212R" ,"213R", "221R", "222R" ,"223R",
                 "311D" ,"312D" ,"313D" ,"321D", "323D" ,"322D","311R" ,"312R" ,"313R" ,"321R", "322R" ,"323R" ,
                 "411D" ,"412D" ,"413D" ,"421D" ,"422D" ,"423D", "411R", "412R" ,"413R" ,"421R" ,"422R" ,"423R",
                 "511D" ,"512D" ,"513D" ,"521D" ,"522D", "523D", "511R", "512R" ,"513R" ,"521R", "522R" ,"523R",
                 "611D" ,"612D" ,"613D", "621D" ,"622D", "623D",  "611R", "612R","613R", "621R" ,"622R", "623R")

#ordering

tab_taxa_order = tab_taxa %>% dplyr::select(OTUID, vector_order, taxonomy)

tab_order_metadata = tab_taxa_order %>% column_to_rownames(var = "OTUID") %>% t() %>% 
  as.data.frame() %>% rownames_to_column(var = "SampleID") %>% inner_join(metadata) 
  


#season
tab_season = tab_order_metadata %>% arrange(Season) %>%dplyr::select(-overhang:-LIB) %>%  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_if(is.character, as.numeric)
vector_season = c(rep("Dry", 36), rep("Rainy", 36))

#polygon
tab_polygon = tab_order_metadata %>% arrange(Poligono)%>% dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)
vector_polygon = c(rep("P1", 12),rep("P2", 12), rep("P3", 12),
                   rep("P4", 12),rep("P5", 12),rep("P6", 12))

#season-polygon
tab_polygon_dry = tab_order_metadata %>% filter(Season=="Dry") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
vector_polygon_dry = c(rep("P1", 6),rep("P2", 6), rep("P3", 6),
                   rep("P4", 6),rep("P5", 6),rep("P6", 6))

tab_polygon_rainy = tab_order_metadata %>% filter(Season=="Rainy") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
vector_polygon_rainy = c(rep("P1", 6),rep("P2", 6), rep("P3", 6),
                   rep("P4", 6),rep("P5", 6),rep("P6", 6))

#polygon-season
tab_p1 = tab_order_metadata %>% filter(Poligono=="P1") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
tab_p2 = tab_order_metadata %>% filter(Poligono=="P2") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>%  
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
tab_p3 = tab_order_metadata %>% filter(Poligono=="P3") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>%   column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)
tab_p4 = tab_order_metadata %>% filter(Poligono=="P4") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>%   column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)
tab_p5 = tab_order_metadata %>% filter(Poligono=="P5") %>% arrange(Season) %>%dplyr::select(-overhang:-LIB)%>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
tab_p6 = tab_order_metadata %>% filter(Poligono=="P6") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB)%>%   column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)


vector_p = c(rep("Dry", 6), rep("Rainy", 6))
```


```{r}
#polygon-paired
tab_p12 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P2") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
vector_p12 = c(rep("P1", 12), rep("P2", 12))


tab_p13 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P3") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p13 = c(rep("P1", 12), rep("P3", 12))


tab_p14 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P4") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p14 = c(rep("P1", 12), rep("P4", 12))


tab_p15 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P5") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p15 = c(rep("P1", 12), rep("P5", 12))

tab_p16 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P6") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p16 = c(rep("P1", 12), rep("P6", 12))


tab_p23 = tab_order_metadata %>% filter(Poligono=="P2"|Poligono=="P3") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
vector_p23 = c(rep("P2", 12), rep("P3", 12))



tab_p24 = tab_order_metadata %>% filter(Poligono=="P2"|Poligono=="P4") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p24 = c(rep("P2", 12), rep("P4", 12))


tab_p25 = tab_order_metadata %>% filter(Poligono=="P2"|Poligono=="P5") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p25 = c(rep("P2", 12), rep("P5", 12))

tab_p26 = tab_order_metadata %>% filter(Poligono=="P2"|Poligono=="P6") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p26 = c(rep("P2", 12), rep("P6", 12))



tab_p34 = tab_order_metadata %>% filter(Poligono=="P3"|Poligono=="P4") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p34 = c(rep("P3", 12), rep("P4", 12))


tab_p35 = tab_order_metadata %>% filter(Poligono=="P3"|Poligono=="P5") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p35 = c(rep("P3", 12), rep("P5", 12))

tab_p36 = tab_order_metadata %>% filter(Poligono=="P3"|Poligono=="P6") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p36 = c(rep("P3", 12), rep("P6", 12))



tab_p45 = tab_order_metadata %>% filter(Poligono=="P4"|Poligono=="P5") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p45 = c(rep("P4", 12), rep("P5", 12))

tab_p46 = tab_order_metadata %>% filter(Poligono=="P4"|Poligono=="P6") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p46 = c(rep("P4", 12), rep("P6", 12))

tab_p56 = tab_order_metadata %>% filter(Poligono=="P5"|Poligono=="P6") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p56 = c(rep("P5", 12), rep("P6", 12))

```

```{r}
library(ALDEx2) 

#aldex season no salió nada
#aldex_season = aldex(tab_season, conditions = vector_season, mc.samples = 128,denom = "all")
#aldex_season_filt = aldex_season %>% filter(wi.ep < 0.05)

#aldex polygon corriendo
#aldex_polygon = aldex(tab_polygon, conditions = vector_polygon, mc.samples = 128,denom = "all", test = "kw")

#aldex effect of season by polygon
aldex_p1 = aldex(tab_p1, conditions = vector_p, mc.samples = 128,denom = "all")
aldex_p1_filt = aldex_p1 %>% filter(wi.ep <0.05)

aldex_p2 = aldex(tab_p2, conditions = vector_p, mc.samples = 128,denom = "all")
aldex_p2_filt = aldex_p2 %>% filter(wi.ep <0.05)

aldex_p3 = aldex(tab_p3, conditions = vector_p, mc.samples = 128,denom = "all")
aldex_p3_filt = aldex_p3 %>% filter(wi.ep <0.05)

aldex_p4 = aldex(tab_p4, conditions = vector_p, mc.samples = 128,denom = "all")
aldex_p4_filt = aldex_p4 %>% filter(wi.ep <0.05)

aldex_p5 = aldex(tab_p5, conditions = vector_p, mc.samples = 128,denom = "all")
aldex_p5_filt = aldex_p5 %>% filter(wi.ep <0.05)


aldex_p6 = aldex(tab_p6, conditions = vector_p, mc.samples = 128,denom = "all")
aldex_p6_filt = aldex_p6 %>% filter(wi.ep <0.05)



```

```{r}
p1=aldex_p1_filt %>% rownames_to_column(var = "Feature.ID") %>% inner_join(taxa) %>%
    mutate(taxa = case_when(
    str_detect(Taxon, "s__") ~ str_extract(Taxon, "(?<=s__)[^;]+"),  
    str_detect(Taxon, "g__") ~ str_extract(Taxon, "(?<=g__)[^_;]+"),
    str_detect(Taxon, "f__") ~ str_extract(Taxon, "(?<=f__)[^_;]+"),
    str_detect(Taxon, "c__") ~ str_extract(Taxon, "(?<=c__)[^_;]+"),
    str_detect(Taxon, "o__") ~ str_extract(Taxon, "(?<=o__)[^_;]+"),
    TRUE ~ NA_character_
  )) %>%
  mutate(type = case_when(
    diff.btw < 0 ~ "Dry",
    TRUE ~ "Rainy"    )) %>% arrange(-diff.btw)%>%
 mutate(taxa = fct_reorder(taxa, desc(diff.btw))) %>% 
  ggplot(aes(y=diff.btw, x=taxa, fill=type))+geom_col(width = 0.5)+coord_flip()+
  scale_fill_manual(values = c("#2887a1","#A16928"))+
  theme(axis.text.y = element_text(face = "italic"))+
  xlab("ASV")+
  labs(fill = NULL) +  
  theme(legend.position = "top",  
        legend.box = "horizontal") +  
  guides(fill = guide_legend(nrow = 1, byrow = TRUE))



p2=aldex_p2_filt %>% rownames_to_column(var = "Feature.ID") %>% inner_join(taxa) %>%
    mutate(taxa = case_when(
    str_detect(Taxon, "s__") ~ str_extract(Taxon, "(?<=s__)[^;]+"),  
    str_detect(Taxon, "g__") ~ str_extract(Taxon, "(?<=g__)[^_;]+"),
    str_detect(Taxon, "f__") ~ str_extract(Taxon, "(?<=f__)[^_;]+"),
    str_detect(Taxon, "c__") ~ str_extract(Taxon, "(?<=c__)[^_;]+"),
    str_detect(Taxon, "o__") ~ str_extract(Taxon, "(?<=o__)[^_;]+"),
    TRUE ~ NA_character_
  )) %>%
  mutate(type = case_when(
    diff.btw < 0 ~ "Dry",
    TRUE ~ "Rainy"    )) %>% arrange(-diff.btw)%>%
 mutate(taxa = fct_reorder(taxa, desc(diff.btw))) %>% 
  ggplot(aes(y=diff.btw, x=taxa, fill=type))+geom_col()+coord_flip()+
  scale_fill_manual(values = c("#A16928","#2887a1"))+
  theme(axis.text.y = element_text(face = "italic"))+
  xlab("ASV")+
  labs(fill = NULL) +  
  theme(legend.position = "top",  
        legend.box = "horizontal") +  
  guides(fill = guide_legend(nrow = 1, byrow = TRUE))


p3=aldex_p3_filt %>% rownames_to_column(var = "Feature.ID") %>% inner_join(taxa) %>%
    mutate(taxa = case_when(
    str_detect(Taxon, "s__") ~ str_extract(Taxon, "(?<=s__)[^;]+"),  
    str_detect(Taxon, "g__") ~ str_extract(Taxon, "(?<=g__)[^_;]+"),
    str_detect(Taxon, "f__") ~ str_extract(Taxon, "(?<=f__)[^_;]+"),
    str_detect(Taxon, "c__") ~ str_extract(Taxon, "(?<=c__)[^_;]+"),
    str_detect(Taxon, "o__") ~ str_extract(Taxon, "(?<=o__)[^_;]+"),
    TRUE ~ NA_character_
  )) %>%
  filter(!taxa=="k__Fungi") %>% 
  mutate(type = case_when(
    diff.btw < 0 ~ "Dry",
    TRUE ~ "Rainy"    )) %>% arrange(-diff.btw)%>%
 mutate(taxa = fct_reorder(taxa, desc(diff.btw))) %>% 
  ggplot(aes(y=diff.btw, x=taxa, fill=type))+geom_col()+coord_flip()+
  scale_fill_manual(values = c("#A16928","#2887a1"))+
  theme(axis.text.y = element_text(face = "italic"))+
  xlab("ASV")+
  labs(fill = NULL) +  
  theme(legend.position = "top",  
        legend.box = "horizontal") +  
  guides(fill = guide_legend(nrow = 1, byrow = TRUE))


p4=aldex_p4_filt %>% rownames_to_column(var = "Feature.ID") %>% inner_join(taxa) %>%
    mutate(taxa = case_when(
    str_detect(Taxon, "s__") ~ str_extract(Taxon, "(?<=s__)[^;]+"),  
    str_detect(Taxon, "g__") ~ str_extract(Taxon, "(?<=g__)[^_;]+"),
    str_detect(Taxon, "f__") ~ str_extract(Taxon, "(?<=f__)[^_;]+"),
    str_detect(Taxon, "c__") ~ str_extract(Taxon, "(?<=c__)[^_;]+"),
    str_detect(Taxon, "o__") ~ str_extract(Taxon, "(?<=o__)[^_;]+"),
    TRUE ~ NA_character_
  )) %>%
  filter(!taxa=="k__Fungi") %>%
  group_by(taxa) %>%
  mutate(repeat_count = row_number() * (n() > 1)) %>%
  ungroup() %>%
  mutate(taxa = ifelse(repeat_count > 0, paste0(taxa,repeat_count), taxa)) %>%
  dplyr::select(-repeat_count)  %>%   
  mutate(type = case_when(
    diff.btw < 0 ~ "Dry",
    TRUE ~ "Rainy"    )) %>% arrange(-diff.btw)%>%
 mutate(taxa = fct_reorder(taxa, desc(diff.btw))) %>% 
  ggplot(aes(y=diff.btw, x=taxa, fill=type))+geom_col()+coord_flip()+
  scale_fill_manual(values = c("#A16928","#2887a1"))+
  theme(axis.text.y = element_text(face = "italic"))+
  xlab("ASV")+
  labs(fill = NULL) +  
  theme(legend.position = "top",  
        legend.box = "horizontal") +  
  guides(fill = guide_legend(nrow = 1, byrow = TRUE))





p5=aldex_p5_filt %>% rownames_to_column(var = "Feature.ID") %>% inner_join(taxa) %>%
    mutate(taxa = case_when(
    str_detect(Taxon, "s__") ~ str_extract(Taxon, "(?<=s__)[^;]+"),  
    str_detect(Taxon, "g__") ~ str_extract(Taxon, "(?<=g__)[^_;]+"),
    str_detect(Taxon, "f__") ~ str_extract(Taxon, "(?<=f__)[^_;]+"),
    str_detect(Taxon, "c__") ~ str_extract(Taxon, "(?<=c__)[^_;]+"),
    str_detect(Taxon, "o__") ~ str_extract(Taxon, "(?<=o__)[^_;]+"),
    TRUE ~ NA_character_
  )) %>%
  filter(!taxa=="k__Fungi") %>%
  group_by(taxa) %>%
  mutate(repeat_count = row_number() * (n() > 1)) %>%
  ungroup() %>%
  mutate(taxa = ifelse(repeat_count > 0, paste0(taxa,repeat_count), taxa)) %>%
  dplyr::select(-repeat_count)  %>%   
  mutate(type = case_when(
    diff.btw < 0 ~ "Dry",
    TRUE ~ "Rainy"    )) %>% arrange(-diff.btw)%>%
 mutate(taxa = fct_reorder(taxa, desc(diff.btw))) %>% 
  ggplot(aes(y=diff.btw, x=taxa, fill=type))+geom_col()+coord_flip()+
  scale_fill_manual(values = c("#A16928","#2887a1"))+
  theme(axis.text.y = element_text(face = "italic"))+
  xlab("ASV")+
  labs(fill = NULL) +  
  theme(legend.position = "top",  
        legend.box = "horizontal") +  
  guides(fill = guide_legend(nrow = 1, byrow = TRUE))




p6=aldex_p6_filt %>% rownames_to_column(var = "Feature.ID") %>% inner_join(taxa) %>%
    mutate(taxa = case_when(
    str_detect(Taxon, "s__") ~ str_extract(Taxon, "(?<=s__)[^;]+"),  
    str_detect(Taxon, "g__") ~ str_extract(Taxon, "(?<=g__)[^_;]+"),
    str_detect(Taxon, "f__") ~ str_extract(Taxon, "(?<=f__)[^_;]+"),
    str_detect(Taxon, "c__") ~ str_extract(Taxon, "(?<=c__)[^_;]+"),
    str_detect(Taxon, "o__") ~ str_extract(Taxon, "(?<=o__)[^_;]+"),
    TRUE ~ NA_character_
  )) %>%
  mutate(taxa = ifelse(taxa == "Wilcoxina_rehmii", paste0(taxa, "*"), taxa)) %>% 
  filter(!taxa=="k__Fungi") %>%
  group_by(taxa) %>%
  mutate(repeat_count = row_number() * (n() > 1)) %>%
  ungroup() %>%
  mutate(taxa = ifelse(repeat_count > 0, paste0(taxa,repeat_count), taxa)) %>%
  dplyr::select(-repeat_count)  %>%   
  mutate(type = case_when(
    diff.btw < 0 ~ "Dry",
    TRUE ~ "Rainy"    )) %>% arrange(-diff.btw)%>%
 mutate(taxa = fct_reorder(taxa, desc(diff.btw))) %>% 
  ggplot(aes(y=diff.btw, x=taxa, fill=type))+geom_col()+coord_flip()+
  scale_fill_manual(values = c("#2887a1"))+
  theme(axis.text.y = element_text(face = "italic"))+
  xlab("ASV")+
  labs(fill = NULL) +  
  theme(legend.position = "top",  
        legend.box = "horizontal",
         axis.text.x = element_text(hjust = 1) ) +  
  guides(fill = guide_legend(nrow = 1, byrow = TRUE))

```


```{r}
library(cowplot)

p=   aldex_p2_filt  %>% rownames_to_column(var = "ID") %>% 
  mutate(type = case_when(
    diff.btw < 0 ~ "Dry",
    TRUE ~ "Rainy"    ))%>% 
  ggplot(aes(y=diff.btw, x=ID, fill=type))+geom_col()+
  scale_fill_manual(name="",values = c("#A16928","#2887a1"))+
    guides(fill = guide_legend(nrow = 1, byrow = TRUE))+theme(  
      legend.box = "horizontal" ,
      legend.title = element_text(hjust = 0.5),  
        legend.spacing.x = unit(0.5, 'cm'))


leg <- cowplot::get_legend(p)


all1=plot_grid(p1+theme(legend.position = "none",axis.title.x = element_blank()),
          p2+theme(legend.position = "none", axis.title.x = element_blank()),
          p3+theme(legend.position = "none"), ncol =1, align = "v", 
          labels = c("A) P1", "C) P2", "E) P3"), label_x = -0.03)

all2=plot_grid(p4+theme(legend.position = "none", axis.title = element_blank()),
          p5+theme(legend.position = "none", axis.title = element_blank()),
          p6+theme(legend.position = "none", axis.title.y = element_blank()), ncol =1,
          align = "v",labels = c("B) P4", "D) P5", "F) P6"),label_x = -0.05)



all=plot_grid(all1,all2)

alls=plot_grid(leg, all, ncol = 1, rel_heights = c(0.1,1))

ggsave("aldex_polss.png", plot = alls, device = "png", width = 14, height = 16)

```

```{r}
aldex_polp = function(x, conds){
aldex = aldex(x, conditions = conds, mc.samples = 128,denom = "all")
aldex_filt = aldex %>% filter(wi.ep <0.05)
return(aldex_filt)
}

aldex_polp2 = function(x, conds){
aldex = aldex(x, conditions = conds, mc.samples = 128,denom = "all")
aldex_filt = aldex %>% filter(wi.eBH <0.05)
return(aldex_filt)
}
library(dplyr)
library(purrr)

# Listar las tablas y sus correspondientes vectores
datos_list <- list(
  tab_p12 = tab_p12,
  tab_p13 = tab_p13,
  tab_p14 = tab_p14,
  tab_p15 = tab_p15,
  tab_p16 = tab_p16,
  tab_p23 = tab_p23,
  tab_p24 = tab_p24,
  tab_p25 = tab_p25,
  tab_p26 = tab_p26,
  tab_p34 = tab_p34,
  tab_p35 = tab_p35,
  tab_p36 = tab_p36,
  tab_p45 = tab_p45,
  tab_p46 = tab_p46,
  tab_p56 = tab_p56
)

# Listar los vectores de condiciones
vectores_list <- list(
  vector_p12 = vector_p12,
  vector_p13 = vector_p13,
  vector_p14 = vector_p14,
  vector_p15 = vector_p15,
  vector_p16 = vector_p16,
  vector_p23 = vector_p23,
  vector_p24 = vector_p24,
  vector_p25 = vector_p25,
  vector_p26 = vector_p26,
  vector_p34 = vector_p34,
  vector_p35 = vector_p35,
  vector_p36 = vector_p36,
  vector_p45 = vector_p45,
  vector_p46 = vector_p46,
  vector_p56 = vector_p56
)

# Aplicar la función aldex_polp a cada conjunto de datos y sus correspondientes vectores
resultados <- map2(datos_list, vectores_list, aldex_polp)
resultados2 <- map2(datos_list, vectores_list, aldex_polp2)


```

