---
title: "aldex2"
output: html_document
date: "2024-06-03"
---

# ALDEx2

- Load data and packages and format

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(qiime2R)
library(ComplexHeatmap)
library(circlize)
library(viridis)
library(ggh4x)

tab <- read_qza("../Data/table_SMOQ_filt.qza")$data %>% as.data.frame() %>% 
rownames_to_column(var = "Feature.ID") 
taxa<- qiime2R::read_qza("../Data/taxonomy_SMOQ_ver10.qza")$data %>% as.data.frame()
metadata<- read.delim("../Data/its_map.txt")

tab_tax<- tab %>% inner_join(taxa) %>% 
  dplyr::select(-Feature.ID) %>% separate("Taxon", into = c("k", "p", "c", "o", "f", "genus", "s", "sh"), sep = ";") %>% group_by(genus) %>% summarise_if(is.numeric, sum) %>% drop_na() %>% 
      mutate(genus = sub("^g__", "", genus))


tab_taxa<- tab_tax %>% dplyr::select(taxonomy=genus,`121D`:`221D`)

vector_order<- c("111D" , "112D", "113D" ,"121D", "122D" ,"123D", "111R" ,"112R", "113R", "121R", "122R" ,"123R",
                 "211D" ,"212D" ,"213D" ,"221D" ,"222D" ,"223D", "211R" ,"212R" ,"213R", "221R", "222R" ,"223R",
                 "311D" ,"312D" ,"313D" ,"321D", "323D" ,"322D","311R" ,"312R" ,"313R" ,"321R", "322R" ,"323R" ,
                 "411D" ,"412D" ,"413D" ,"421D" ,"422D" ,"423D", "411R", "412R" ,"413R" ,"421R" ,"422R" ,"423R",
                 "511D" ,"512D" ,"513D" ,"521D" ,"522D", "523D", "511R", "512R" ,"513R" ,"521R", "522R" ,"523R",
                 "611D" ,"612D" ,"613D", "621D" ,"622D", "623D",  "611R", "612R","613R", "621R" ,"622R", "623R")

#ordering

tab_taxa_order = tab_taxa %>% dplyr::select(taxonomy, vector_order)


tab_order_metadata = tab_taxa_order %>% column_to_rownames(var = "taxonomy") %>% t() %>% 
  as.data.frame() %>% rownames_to_column(var = "SampleID") %>% inner_join(metadata) 
  


#season
tab_season = tab_order_metadata %>% arrange(Season) %>%dplyr::select(-overhang:-LIB) %>%  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_if(is.character, as.numeric)
vector_season = c(rep("Dry", 36), rep("Rainy", 36))

#polygon
tab_polygon = tab_order_metadata %>% arrange(Poligono)%>% dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)
vector_polygon = c(rep("P1", 12),rep("P2", 12), rep("P3", 12),
                   rep("P4", 12),rep("P5", 12),rep("P6", 12))

#season-polygon
tab_polygon_dry = tab_order_metadata %>% filter(Season=="Dry") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
vector_polygon_dry = c(rep("P1", 6),rep("P2", 6), rep("P3", 6),
                   rep("P4", 6),rep("P5", 6),rep("P6", 6))

tab_polygon_rainy = tab_order_metadata %>% filter(Season=="Rainy") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
vector_polygon_rainy = c(rep("P1", 6),rep("P2", 6), rep("P3", 6),
                   rep("P4", 6),rep("P5", 6),rep("P6", 6))

#polygon-season
tab_p1 = tab_order_metadata %>% filter(Poligono=="P1") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
tab_p2 = tab_order_metadata %>% filter(Poligono=="P2") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>%  
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
tab_p3 = tab_order_metadata %>% filter(Poligono=="P3") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>%   column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)
tab_p4 = tab_order_metadata %>% filter(Poligono=="P4") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB) %>%   column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric)
tab_p5 = tab_order_metadata %>% filter(Poligono=="P5") %>% arrange(Season) %>%dplyr::select(-overhang:-LIB)%>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
tab_p6 = tab_order_metadata %>% filter(Poligono=="P6") %>% arrange(Season)%>%dplyr::select(-overhang:-LIB)%>%   column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)


vector_p = c(rep("Dry", 6), rep("Rainy", 6))
```


```{r, message=FALSE, warning=FALSE}
#polygon-paired
tab_p12 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P2") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
vector_p12 = c(rep("P1", 12), rep("P2", 12))


tab_p13 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P3") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p13 = c(rep("P1", 12), rep("P3", 12))


tab_p14 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P4") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p14 = c(rep("P1", 12), rep("P4", 12))


tab_p15 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P5") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p15 = c(rep("P1", 12), rep("P5", 12))

tab_p16 = tab_order_metadata %>% filter(Poligono=="P1"|Poligono=="P6") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p16 = c(rep("P1", 12), rep("P6", 12))


tab_p23 = tab_order_metadata %>% filter(Poligono=="P2"|Poligono=="P3") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)
vector_p23 = c(rep("P2", 12), rep("P3", 12))



tab_p24 = tab_order_metadata %>% filter(Poligono=="P2"|Poligono=="P4") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p24 = c(rep("P2", 12), rep("P4", 12))


tab_p25 = tab_order_metadata %>% filter(Poligono=="P2"|Poligono=="P5") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p25 = c(rep("P2", 12), rep("P5", 12))

tab_p26 = tab_order_metadata %>% filter(Poligono=="P2"|Poligono=="P6") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p26 = c(rep("P2", 12), rep("P6", 12))



tab_p34 = tab_order_metadata %>% filter(Poligono=="P3"|Poligono=="P4") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p34 = c(rep("P3", 12), rep("P4", 12))


tab_p35 = tab_order_metadata %>% filter(Poligono=="P3"|Poligono=="P5") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p35 = c(rep("P3", 12), rep("P5", 12))

tab_p36 = tab_order_metadata %>% filter(Poligono=="P3"|Poligono=="P6") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p36 = c(rep("P3", 12), rep("P6", 12))



tab_p45 = tab_order_metadata %>% filter(Poligono=="P4"|Poligono=="P5") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p45 = c(rep("P4", 12), rep("P5", 12))

tab_p46 = tab_order_metadata %>% filter(Poligono=="P4"|Poligono=="P6") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p46 = c(rep("P4", 12), rep("P6", 12))

tab_p56 = tab_order_metadata %>% filter(Poligono=="P5"|Poligono=="P6") %>% arrange(Poligono)%>%dplyr::select(-overhang:-LIB) %>% 
  column_to_rownames(var = "SampleID") %>% t() %>% as.data.frame() %>% mutate_all(as.numeric) %>%
  filter(rowSums(.) != 0)

vector_p56 = c(rep("P5", 12), rep("P6", 12))

```

```{r}
source("../Scripts/plot_volcanop.R")
```


```{r, warning=FALSE, message=FALSE, eval=FALSE}
library(ALDEx2) 

aldex_p1 = aldex(tab_p1, conditions = vector_p, mc.samples = 128,denom = "all")

aldex_p2 = aldex(tab_p2, conditions = vector_p, mc.samples = 128,denom = "all")

aldex_p3 = aldex(tab_p3, conditions = vector_p, mc.samples = 128,denom = "all")

aldex_p4 = aldex(tab_p4, conditions = vector_p, mc.samples = 128,denom = "all")

aldex_p5 = aldex(tab_p5, conditions = vector_p, mc.samples = 128,denom = "all")

aldex_p6 = aldex(tab_p6, conditions = vector_p, mc.samples = 128,denom = "all")

```

```{r, echo=FALSE}
aldex_p1 <- readRDS("../Data/aldex_p1.RDS")
aldex_p2 <- readRDS("../Data/aldex_p2.RDS")
aldex_p3 <- readRDS("../Data/aldex_p3.RDS")
aldex_p4 <- readRDS("../Data/aldex_p4.RDS")
aldex_p5 <- readRDS("../Data/aldex_p5.RDS")
aldex_p6 <- readRDS("../Data/aldex_p6.RDS")

```


```{r}
p1= plot_volcanop(aldex_p1, taxa)
p2= plot_volcanop(aldex_p2, taxa)
p3= plot_volcanop(aldex_p3, taxa)
p4= plot_volcanop(aldex_p4, taxa)
p5= plot_volcanop(aldex_p5, taxa)
p6= plot_volcanop(aldex_p6, taxa)

```


```{r, warning=FALSE, message=FALSE, fig.align='center', fig.height=10, fig.width=8}
library(cowplot)

all=plot_grid(p1 +xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")),
              p2+xlab("")+ylab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")),
              p3 +xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), 
              p4+ xlab("")+ylab("")+theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), 
              p5+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")),
              p6+ ylab("")+theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), 
              ncol = 2, nrow = 3, align = "hv", labels = "AUTO")

all


ggsave("../Plots/aldex_polss.png", plot = all, device = "png", width = 8, height = 10)

```

```{r}
aldex_polp = function(x, conds){
aldex = aldex(x, conditions = conds, mc.samples = 128,denom = "all")
#aldex_filt = aldex %>% filter(wi.ep <0.05)
return(aldex)
}

#x = aldex_polp(x=tab_p4, conds = vector_p)

aldex_polp2 = function(x, conds){
aldex = aldex(x, conditions = conds, mc.samples = 128,denom = "all")
aldex_filt = aldex %>% filter(wi.eBH <0.05)
return(aldex_filt)
}
library(dplyr)
library(purrr)

# Listar las tablas y sus correspondientes vectores
datos_list <- list(
  tab_p12 = tab_p12,
  tab_p13 = tab_p13,
  tab_p14 = tab_p14,
  tab_p15 = tab_p15,
  tab_p16 = tab_p16,
  tab_p23 = tab_p23,
  tab_p24 = tab_p24,
  tab_p25 = tab_p25,
  tab_p26 = tab_p26,
  tab_p34 = tab_p34,
  tab_p35 = tab_p35,
  tab_p36 = tab_p36,
  tab_p45 = tab_p45,
  tab_p46 = tab_p46,
  tab_p56 = tab_p56
)

# Listar los vectores de condiciones
vectores_list <- list(
  vector_p12 = vector_p12,
  vector_p13 = vector_p13,
  vector_p14 = vector_p14,
  vector_p15 = vector_p15,
  vector_p16 = vector_p16,
  vector_p23 = vector_p23,
  vector_p24 = vector_p24,
  vector_p25 = vector_p25,
  vector_p26 = vector_p26,
  vector_p34 = vector_p34,
  vector_p35 = vector_p35,
  vector_p36 = vector_p36,
  vector_p45 = vector_p45,
  vector_p46 = vector_p46,
  vector_p56 = vector_p56
)
```


```{r, eval=FALSE}
# Aplicar la función aldex_polp a cada conjunto de datos y sus correspondientes vectores
resultados <- map2(datos_list, vectores_list, aldex_polp)
#resultados2 <- map2(datos_list, vectores_list, aldex_polp2)


```

```{r}
library(tidyverse)
source("../Scripts/plot_volcano.R")

```

```{r, echo=FALSE}
#saveRDS(resultados, "../Data/resultados.RDS")
resultados = readRDS("../Data/resultados.RDS")
```

```{r, message=FALSE, warning=FALSE, fig.align='center', fig.height=13, fig.width=11}

library(cowplot)

pp1= plot_volcano(x = resultados[[1]], taxa = taxa)
pp2= plot_volcano(x = resultados[[2]], taxa = taxa)
pp3= plot_volcano(x = resultados[[3]], taxa = taxa)
pp4= plot_volcano(x = resultados[[4]], taxa = taxa)
pp5= plot_volcano(x = resultados[[5]], taxa = taxa)
pp6= plot_volcano(x = resultados[[6]], taxa = taxa)
pp7= plot_volcano(x = resultados[[7]], taxa = taxa)
pp8= plot_volcano(x = resultados[[8]], taxa = taxa)
pp9= plot_volcano(x = resultados[[9]], taxa = taxa)
pp10= plot_volcano(x = resultados[[10]], taxa = taxa)
pp11= plot_volcano(x = resultados[[11]], taxa = taxa)
pp12= plot_volcano(x = resultados[[12]], taxa = taxa)
pp13= plot_volcano(x = resultados[[13]], taxa = taxa)
pp14= plot_volcano(x = resultados[[14]], taxa = taxa)
pp15= plot_volcano(x = resultados[[15]], taxa = taxa)


pps=plot_grid(pp1+xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), pp2+ylab("")+xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), pp3+ylab("")+xlab("")+ theme(plot.margin = unit(c(0.01, 0.1, 0.01, 0.01), "cm")), 
              pp4+xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), pp5+ylab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm"))+xlab(""), pp6+ylab("")+xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), 
              pp7+xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), pp8+ylab("")+xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), pp9+xlab("")+ylab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")),
              pp10+xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")),pp11+ylab("")+xlab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), pp12+ylab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm"))+xlab(""), 
              pp13+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")),pp14+ylab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), pp15+ylab("")+ theme(plot.margin = unit(c(0.01, 0.01, 0.01, 0.01), "cm")), ncol = 3, nrow = 5, align = "hv", labels = "AUTO")


pps


ggsave("../Plots/aldex_polss_volcano_bh.png", plot = pps, device = "png", width = 11, height = 13, dpi = 300)

```

