---
title: "alpha diversity"
output: html_document
date: "2024-05-16"
---

# Alpha diversity 


-   Load files and packages

```{r, message=FALSE, warning=FALSE}
library(qiime2R)
library(tidyverse)
library(hillR)
library(ggpubr)

table_otus<- read_qza("../Data/table_SMOQ_filt.qza")$data
table_asvs<- read_qza("../Data/table_SMDR.qza")$data

meta<- read.delim("../Data/its_map.txt")
```

-   Calculate hill numbers and join

```{r, message=FALSE, warning=FALSE}
hill0<- hill_taxa(comm = table_otus, q = 0, MARGIN = 2)
hill1<- hill_taxa(comm = table_otus, q = 1, MARGIN = 2)
hill2<- hill_taxa(comm = table_otus, q = 2, MARGIN = 2)

hill0a<- hill_taxa(comm = table_asvs, q = 0, MARGIN = 2)
hill1a<- hill_taxa(comm = table_asvs, q = 1, MARGIN = 2)
hill2a<- hill_taxa(comm = table_asvs, q = 2, MARGIN = 2)


q0<- as.data.frame(hill0) %>% #colMeans() %>% 
  round() %>% as.data.frame() %>% dplyr::rename(q="hill0") %>% 
  mutate(order="q0") %>% rownames_to_column(var = "SampleID")
q1<- as.data.frame(hill1) %>% #colMeans() %>% 
  round() %>% as.data.frame()%>% dplyr::rename(q="hill1") %>% 
  mutate(order="q1")%>% rownames_to_column(var = "SampleID")
q2<- as.data.frame(hill2) %>% #colMeans() %>% 
  round() %>% as.data.frame() %>% dplyr::rename(q="hill2") %>% 
  mutate(order="q2")%>% rownames_to_column(var = "SampleID")


q0a<- as.data.frame(hill0a) %>% #colMeans() %>% 
  round() %>% as.data.frame() %>% dplyr::rename(q="hill0a") %>% 
  mutate(order="q0") %>% rownames_to_column(var = "SampleID")
q1a<- as.data.frame(hill1a) %>% #colMeans() %>% 
  round() %>% as.data.frame()%>% dplyr::rename(q="hill1a") %>% 
  mutate(order="q1")%>% rownames_to_column(var = "SampleID")
q2a<- as.data.frame(hill2a) %>% #colMeans() %>% 
  round() %>% as.data.frame() %>% dplyr::rename(q="hill2a") %>% 
  mutate(order="q2")%>% rownames_to_column(var = "SampleID")

qs<- q0 %>% full_join(q1) %>% full_join(q2) %>% pivot_longer(
  cols = c(-SampleID,-order), values_to = "val", names_to = "ids") %>% inner_join(meta) %>% unite("interact",c("Poligono", "Season"),remove = F)


qsa<- q0a %>% full_join(q1a) %>% full_join(q2a) %>% pivot_longer(
  cols = c(-SampleID,-order), values_to = "val", names_to = "ids") %>% inner_join(meta)%>% unite("interact",c("Poligono", "Season"),remove = F)

#qs<-qsa

#write.csv(qs, "../Data/qs.csv", row.names = F)

```


```{r, warning=FALSE, message=FALSE}
#install.packages("ggpubr")
library(ggpubr)
depth<- read.delim("../Data/depth.txt")

q0_data<- q0 %>% dplyr::rename("q0"="q") %>% dplyr::select(-order)
q1_data<- q1 %>% dplyr::rename("q1"="q") %>% dplyr::select(-order)
q2_data<- q2 %>% dplyr::rename("q2"="q") %>% dplyr::select(-order)

q_data<- q0_data %>% inner_join(q1_data) %>% inner_join(q2_data) %>% 
  inner_join(depth, by = c("SampleID"="Sample.ID"))


q0_vs_depth_fltr <- ggscatter(q_data , 
                         x = "Frequency", 
                         y = "q0", 
                         xlab= "Sequencing depth (number of reads)",
                         ylab = "q=0",
                         #ylab="Alpha diversity q=0 (effective number of total ASVs)",
   add = "reg.line",  # Add regression line
   add.params = list(color = "#B03A2E", fill = "#566573"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
   cor.coeff.args = list(method = "pearson", label.x = 3, label.sep = "\n")
   )+theme_grey()+
  theme(legend.title = element_blank(), legend.position = "none")+ labs(y=expression(paste(italic("q"), "=0", " (number of total OTUs/OTUs)")))

q1_vs_depth_fltr <- ggscatter(q_data, 
                         x = "Frequency", 
                         y = "q1", 
                         xlab= "Sequencing depth (number of reads)",
                         ylab = "q=1",
                         #ylab="Alpha diversity q=1 (effective number of total ASVs)",
   add = "reg.line",  # Add regression line
   add.params = list(color = "#B03A2E", fill = "#566573"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
   cor.coeff.args = list(method = "pearson", label.x = 3, label.sep = "\n")
   )+theme_grey()+
  theme(legend.title = element_blank(), legend.position = "none")+ labs(y=expression(paste(italic("q"), "=1", " (number of frequent OTUs/OTUs)")))



q2_vs_depth_fltr <- ggscatter(q_data, 
                         x = "Frequency", 
                         y = "q2", 
                         xlab= "Sequencing depth (number of reads)",
                         ylab = "q=2",
                         #ylab="Alpha diversity q=2 (effective number of total ASVs)",
   add = "reg.line",  # Add regression line
   add.params = list(color = "#B03A2E", fill = "#566573"), # Customize reg. line
   conf.int = TRUE, # Add confidence interval
   cor.coef = TRUE, # Add correlation coefficient. see ?stat_cor
   cor.coeff.args = list(method = "pearson", label.x = 3, label.sep = "\n")
   )+theme_grey()+
  theme(legend.title = element_blank(), legend.position = "none")+ labs(y=expression(paste(italic("q"), "=2", " (number of dominant OTUs/OTUs)")))


library(ggplot2)
library(cowplot)

#save plots

#Combine plot
title_corr_plot <- ggdraw() + draw_label("Alpha diversity depth correlation with samples")
correlation_plot_q012_fltr <- plot_grid(q0_vs_depth_fltr,q1_vs_depth_fltr,q2_vs_depth_fltr, labels = c("A", "B", "C"), nrow = 1, rel_heights = c(1, 1, 1))
correlation_plot_q012_fltr

ggsave('../Plots/alpha_corr.png', width = 11, height = 6, dpi = 300, plot =correlation_plot_q012_fltr)


```

```{r}
lm.q0<-qs %>% filter(order=="q0") 
model0<- lm(val ~ Poligono*Season, data = lm.q0)
car::leveneTest(val ~ Poligono*Season, data = lm.q0)
plot(model0, which = 2)
#shapiro.test(model0$residuals)
a0<- aov(model0)
a00<-summary(a0)
pvalues0<-a00[[1]][[5]]
modelinteract0<- aov(lm(val ~ interact, data = lm.q0))
agricolae::HSD.test(modelinteract0, "interact", console = TRUE)
let0<-agricolae::HSD.test(modelinteract0, "interact", console = TRUE)$groups %>% 
  mutate(order="q0")


lm.q1<-qs %>% filter(order=="q1") 
model1<- lm(val ~ Poligono*Season, data = lm.q1)
car::leveneTest(val ~ Poligono*Season, data = lm.q1)
plot(model1, which = 2)
#shapiro.test(model1$residuals)
a1<- aov(model1)
a11<-summary(a1)
pvalues1<-a11[[1]][[5]]
modelinteract1<- aov(lm(val ~ interact, data = lm.q1))
agricolae::HSD.test(modelinteract1, "interact", console = TRUE)
let1<-agricolae::HSD.test(modelinteract1, "interact", console = TRUE)$groups%>% 
  mutate(order="q1")


lm.q2<-qs %>% filter(order=="q2") 
model2<- lm(val ~ Poligono*Season, data = lm.q2)
car::leveneTest(val ~ Poligono*Season, data = lm.q2)
plot(model2, which = 2)
#shapiro.test(model2$residuals)
a2<- aov(model2)
a22<-summary(a2)
pvalues2<-a22[[1]][[5]]
modelinteract2<- aov(lm(val ~ interact, data = lm.q2))
let2<-agricolae::HSD.test(modelinteract2, "interact", console = TRUE)$groups%>% 
  mutate(order="q2")

#letters_int<-rbind(let0, let1, let2)#%>% rownames_to_column(var="interact") %>% 
  #dplyr::rename(mean=val)



```

```{r, message=FALSE, warning=FALSE}
library(ggh4x)
library(rcartocolor)
#colors<-viridis::turbo(6, alpha = 1, begin = 0, end = 1, direction = 1)
colors = carto_pal(6, "Safe")
my_colors=carto_pal(2, "Earth")
my_colors

strip <- strip_themed(background_x = elem_list_rect(fill = colors))

labels <- let0 %>% rownames_to_column(var = "interact") %>% 
  separate("interact", c("Poligono", "Season"), remove = F)

labels<- labels  %>% mutate(val=1600)


a <- qs %>%   
  mutate(
    orders = case_when(
     order == "q0" ~ "q=0",
    order == "q1" ~ "q=1",
   order == "q2" ~ "q=2" )) %>%filter(
    order=="q0") %>% 
    ggbarplot(x = "Season", y = "val", fill="Season", facet.by = "Poligono", add=c("mean_se", "jitter"))+
  facet_grid2(vars(orders), vars(Poligono), scales = "free", strip = strip)+
  theme(axis.text.x = element_blank() ,
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())+
  ylab("Effective number of OTUs")+
 stat_compare_means(aes(group = Season), method = "t.test",label = "p.format")+
  scale_fill_manual(values = c("#A16928" ,"#2887a1"))+theme_grey()+
     theme(axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 14, face = "bold", color="white"),
        strip.text.y = element_text(size = 16, face="bold.italic", colour = "white"),
       axis.title = element_text(size = 18))+
  geom_label(data = labels, aes(label=groups),
                hjust = 1, vjust = 1)+
   ggtitle(paste0("Polygon =",signif(pvalues0[1], digits = 3), "; ",
                  "Season =",signif(pvalues0[2], digits = 3), "; ",
                  "Polygon*Season =",signif(pvalues0[3], digits = 3)))+ theme(
                  strip.background.y = element_rect(
     color="grey", fill="black", size=1, linetype="solid"),
     strip.background.x = element_rect(colour = "black", linetype = "solid", size = 1))

 
labels <- let1 %>% rownames_to_column(var = "interact") %>% 
  separate("interact", c("Poligono", "Season"), remove = F)

labels<- labels  %>% mutate(val=250)


b <- qs %>%   
  mutate(
    orders = case_when(
     order == "q0" ~ "q=0",
    order == "q1" ~ "q=1",
   order == "q2" ~ "q=2" )) %>%filter(
    order=="q1") %>% 
    ggbarplot(x = "Season", y = "val", fill="Season", facet.by = "Poligono", add=c("mean_se", "jitter"))+
  facet_grid2(vars(orders), vars(Poligono), scales = "free", strip = strip)+
  theme(axis.text.x = element_blank() ,
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())+
  ylab("Effective number of OTUs")+
 stat_compare_means(aes(group = Season), method = "t.test",label = "p.format")+
  scale_fill_manual(values = c("#A16928" ,"#2887a1"))+theme_grey()+
     theme(axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 14, face = "bold", color="white"),
        strip.text.y = element_text(size = 16, face="bold.italic", colour = "white"),
       axis.title = element_text(size = 18))+
  geom_label(data = labels, aes(label=groups),
                hjust = 1, vjust = 1)+
   ggtitle(paste0("Polygon =",signif(pvalues1[1], digits = 3), "; ",
                  "Season =",signif(pvalues1[2], digits = 3), "; ",
                  "Polygon*Season =",signif(pvalues1[3], digits = 3)))+ theme(
                  strip.background.y = element_rect(
     color="grey", fill="black", size=1, linetype="solid"),
     strip.background.x = element_rect(colour = "black", linetype = "solid", size = 1))+
  theme(strip.text.x = element_blank())
 

#strip.background = element_rect(color="black", size=1.5, linetype="solid" ))

labels <- let2 %>% rownames_to_column(var = "interact") %>% 
  separate("interact", c("Poligono", "Season"), remove = F)

labels<- labels  %>% mutate(val=80)

c <- qs %>%   
  mutate(
    orders = case_when(
     order == "q0" ~ "q=0",
    order == "q1" ~ "q=1",
   order == "q2" ~ "q=2" )) %>%filter(
    order=="q2") %>% 
    ggbarplot(x = "Season", y = "val", fill="Season", facet.by = "Poligono", add=c("mean_se", "jitter"))+
  facet_grid2(vars(orders), vars(Poligono), scales = "free", strip = strip)+
  theme(axis.text.x = element_blank() ,
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank())+
  ylab("Effective number of OTUs")+
 stat_compare_means(aes(group = Season), method = "t.test",label = "p.format")+
  scale_fill_manual(values = c("#A16928" ,"#2887a1"))+theme_grey()+
     theme(axis.text.x = element_text(size = 14, colour = "black"), 
      #  axis.ticks.x = element_blank(),
       strip.text.x = element_text(size = 14, face = "bold", color="white"),
        strip.text.y = element_text(size = 16, face="bold.italic", colour = "white"),
       axis.title = element_text(size = 18))+
  geom_label(data = labels, aes(label=groups),
                hjust = 1, vjust = 1)+
   ggtitle(paste0("Polygon =",signif(pvalues2[1], digits = 3), "; ",
                  "Season =",signif(pvalues2[2], digits = 3), "; ",
                  "Polygon*Season =",signif(pvalues2[3], digits = 3)))+ theme(
                  strip.background.y = element_rect(
     color="grey", fill="black", size=1, linetype="solid"),
     strip.background.x = element_rect(colour = "black", linetype = "solid", size = 1))+
  theme(strip.text.x = element_blank())
 

 

```


```{r, message=FALSE, warning=FALSE, fig.align='center', fig.height=11, fig.width=11}
library(cowplot)



alpha<- plot_grid(a + theme(legend.position = "none", axis.title.x = element_blank())+ylab(""),
                  b+theme(legend.position = "none", axis.title.x = element_blank(),
                          axis.title.y = element_text(size = 15)),
                  c+ theme(legend.position = "none")+ylab(""),
                  labels = c("A", "B", "C"),
                  ncol = 1)
alpha

ggsave('../Plots/alpha_nosingletons.png', width = 11, height = 11, dpi = 300, plot =alpha)

```


