---
title: "Guilds"
output: html_document
date: "2024-06-03"
---

- Load data and packages and format

```{r}
library(tidyverse)
library(qiime2R)
library(ComplexHeatmap)
library(circlize)
library(viridis)
library(ggh4x)

tab <- read_qza("../Data/table_SMOQ.qza")$data %>% as.data.frame() %>% 
rownames_to_column(var = "Feature.ID") 
taxa<- qiime2R::read_qza("../Data/taxonomy_SMOQ_ver10.qza")$data %>% as.data.frame()

#tab <- read_qza("../Data/table_SMDR.qza")$data %>% as.data.frame() %>% 
#rownames_to_column(var = "Feature.ID") 
#taxa<- qiime2R::read_qza("../Data/taxonomy_SMDR.qza")$data %>% as.data.frame()


tab_tax<- tab %>% inner_join(taxa)

tab_taxa<- tab_tax %>% dplyr::select(OTUID=Feature.ID, `121D`:`221D`, taxonomy=Taxon)
#tab_taxa<- tab_tax %>% dplyr::select(OTUID=Feature.ID, `111D`:`623R`, taxonomy=Taxon)


#guilds

guild1<- read.delim("../Data/otus/table_otus.guilds_matched.txt", check.names = F) %>% 
 filter(!"Trophic Mode"=="na") %>%
mutate(Guild = str_replace_all(Guild, "\\|", ""))

#guild1<- read.delim("../Data/asvs/table_asvs.guilds_matched.txt", check.names = F) %>% 
 #filter(!"Trophic Mode"=="na") %>%
#mutate(Guild = str_replace_all(Guild, "\\|", ""))
#relabunda<- function(x){(as.data.frame(t(t(x)/colSums(x)))*100)}



guild<- guild1 %>% group_by(Guild) %>% summarise_if(is.numeric, sum)
guild_abund<- relabunda(guild[-1])
guild_abund$Guild<- guild$Guild
guild_abund_filter<- guild_abund %>% filter(Guild %in% c("Ectomycorrhizal",  "Undefined Saprotroph", "Wood Saprotroph")) %>% dplyr::select(-`Taxon Level`)

trophic<- guild1 %>% group_by(`Trophic Mode`)  %>% summarise_if(is.numeric, sum)
trophic_abund<- relabunda(trophic[-1])
trophic_abund$Trophic<- trophic$`Trophic Mode`
trophic_abund_filter<- trophic_abund %>% filter(Trophic %in% c("Pathotroph", "Saprotroph","Symbiotroph"    )) %>% dplyr::select(-`Taxon Level`)


metadata<- read.delim("../Data/its_map.txt")


vector_order<- c("111D" , "112D", "113D" ,"121D", "122D" ,"123D", "111R" ,"112R", "113R", "121R", "122R" ,"123R",
                 "211D" ,"212D" ,"213D" ,"221D" ,"222D" ,"223D", "211R" ,"212R" ,"213R", "221R", "222R" ,"223R",
                 "311D" ,"312D" ,"313D" ,"321D", "323D" ,"322D","311R" ,"312R" ,"313R" ,"321R", "322R" ,"323R" ,
                 "411D" ,"412D" ,"413D" ,"421D" ,"422D" ,"423D", "411R", "412R" ,"413R" ,"421R" ,"422R" ,"423R",
                 "511D" ,"512D" ,"513D" ,"521D" ,"522D", "523D", "511R", "512R" ,"513R" ,"521R", "522R" ,"523R",
                 "611D" ,"612D" ,"613D", "621D" ,"622D", "623D",  "611R", "612R","613R", "621R" ,"622R", "623R")

#ordering
```

- Guilds plot

```{r}
table_guilds <- guild_abund_filter %>%column_to_rownames(var = "Guild") %>% 
  t() %>% as.data.frame() %>% rownames_to_column(var = "SampleID") %>% inner_join(metadata) %>% dplyr::select("SampleID","Ectomycorrhizal", "Undefined Saprotroph",  "Wood Saprotroph"  ,"Poligono",              "Sitio", "Transecto","Season"  ) %>% pivot_longer(cols = c("Ectomycorrhizal", "Undefined Saprotroph",  "Wood Saprotroph"), names_to = "Guild", values_to = "relab")

colors<-viridis::turbo(6, alpha = 1, begin = 0, end = 1, direction = 1)

strip <- strip_themed(background_x = elem_list_rect(fill = colors))

plot_guilds<- table_guilds %>% ggboxplot(x = "Season", y="relab", facet.by = "Poligono", fill="Season")+facet_grid2( Guild~Poligono, scales = "free_y",  strip = strip)+
 stat_compare_means(aes(group = Season), method = "t.test",label = "p.format")+
  scale_fill_manual(values = c("#FE922AFF","#4490FEFF"))+theme_grey()+
  theme(axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 14, face = "bold", color="white"),
        strip.text.y = element_text(size = 14, face = "bold"),
       axis.title = element_text(size = 18))+ theme(
                  strip.background.y = element_rect(
     color="black", fill="black", size=1.5, linetype="solid"),
     strip.text.y = element_text(colour = "white", face = "bold"))+
  ylab("Relative abundance %")

ggsave('../Plots/guilds_otus.png', width =10, height = 8, dpi = 300, plot=plot_guilds)

 
```

```{r}
table_trophic <- trophic_abund_filter %>%column_to_rownames(var = "Trophic") %>% 
  t() %>% as.data.frame() %>% rownames_to_column(var = "SampleID") %>% inner_join(metadata) %>% dplyr::select("SampleID", "Pathotroph" ,  "Saprotroph", "Symbiotroph"  , "Poligono",              "Sitio", "Transecto","Season"  ) %>% pivot_longer(cols = c("Pathotroph" ,  "Saprotroph", "Symbiotroph"  ), names_to = "Trophic", values_to = "relab")

colors<-viridis::turbo(6, alpha = 1, begin = 0, end = 1, direction = 1)

strip <- strip_themed(background_x = elem_list_rect(fill = colors))

plot_trophic<- table_trophic %>% ggboxplot(x = "Season", y="relab", facet.by = "Poligono", fill="Season")+facet_grid2( Trophic~Poligono, scales = "free_y",  strip = strip)+
 stat_compare_means(aes(group = Season), method = "t.test",label = "p.format")+
  scale_fill_manual(values = c("#FE922AFF","#4490FEFF"))+theme_grey()+
  theme(axis.text.x = element_blank(), 
        axis.ticks.x = element_blank(),
        strip.text.x = element_text(size = 14, face = "bold", color="white"),
        strip.text.y = element_text(size = 14, face = "bold"),
       axis.title = element_text(size = 18))+ theme(
                  strip.background.y = element_rect(
     color="black", fill="black", size=1.5, linetype="solid"),
     strip.text.y = element_text(colour = "white", face = "bold"))+
  ylab("Relative abundance %")

ggsave('../Plots/trophic_otus.png', width =10, height = 8, dpi = 300, plot=plot_trophic)


```


