---
title: "Physico-chemicals"
output: html_document
date: "2024-05-16"
---

# Phycochemical characteristics - Both seasons 


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

- Loading packages and data    
```{r, message=FALSE, warning=FALSE}
library(reshape2)
library(picante)
library(readxl)
library(tidyverse)
library(pgirmess)
library(car)
library(ggplot2)
library(ggpubr)
dry<- read_excel("../Data/Fisicoquimicos.xlsx", sheet = "metadata_secas_all") %>% mutate(Season="Dry")
wet<- read_excel("../Data/Fisicoquimicos.xlsx", sheet = "metadata_lluvias_all") %>% mutate(Season="Wet")

# select characteristics in both datasets
drys<- dry %>% dplyr::select( Poligono,Sitio,Transecto,pH,MO,N,P,Season)
wets<- wet %>% dplyr::select(Poligono,Sitio,Transecto,pH,MO,N,P,Season)

env_season<- rbind(drys,wets) %>% mutate(sea=c(rep("D",36), rep("R",36))) %>% unite("SampleID", c("Poligono", "Sitio", "Transecto", "sea"),remove = F, sep = "")

env_season$Poligono<- factor(env_season$Poligono, levels = c(1,2,3,4,5,6),
                             labels = c("P1", "P2", "P3", "P4", "P5", "P6"))
env_season$Season<- factor(env_season$Season)

env_season<-env_season %>%  unite("interact", c("Poligono", "Season"), remove = F)

df <-env_season  %>% column_to_rownames(var="SampleID") %>% dplyr::select(pH,MO,N,P)
dfs=data.frame(scale(df, center = T, scale = T)) #standardize environmental data

df$Poligono<-NA
df$Poligono<-env_season$Poligono
df$Season<-env_season$Season

dfs$Poligono<-NA
dfs$Poligono<-env_season$Poligono

#melted_df=melt(dfs, id="Poligono")
#melted_df=melt(df, id=c("Poligono", "Season"))
#mean_table=Rmisc::summarySE(melted_df, measurevar = "value", groupvars=c("variable","Poligono", "Season"), na.rm = T)

# checking collinearity
cor.table(na.omit(dfs[,1:4]))
```


```{r, message=FALSE, warning=FALSE}
#checking normality and non-parametrics
shapiro.test(env_season$pH)
shapiro.test(env_season$MO)
shapiro.test(env_season$N)
shapiro.test(env_season$P)


k.ph.s<-round(kruskal.test(env_season$pH~env_season$Season)$p.value, digits = 3)
k.ph.p<-round(kruskal.test(env_season$pH~env_season$Poligono)$p.value, digits = 3)
leveneTest(env_season$pH~env_season$Season)
leveneTest(env_season$pH~env_season$Poligono)
k.ph.s
k.ph.p

k.mo.s<-round(kruskal.test(env_season$MO~env_season$Season)$p.value, 3)
k.mo.p<-kruskal.test(env_season$MO~env_season$Poligono)$p.value
leveneTest(env_season$MO~env_season$Season)
leveneTest(env_season$MO~env_season$Poligono)
k.mo.s
k.mo.p

k.n.s<-round(kruskal.test(env_season$N~env_season$Season)$p.value,3)
k.n.p<-round(kruskal.test(env_season$N~env_season$Poligono)$p.value,3)
leveneTest(env_season$N~env_season$Season)
leveneTest(env_season$N~env_season$Poligono)
k.n.s
k.n.p

k.p.s<-round(kruskal.test(env_season$P~env_season$Season)$p.value,3)
k.p.p<-kruskal.test(env_season$P~env_season$Poligono)$p.value
leveneTest(env_season$P~env_season$Season)
leveneTest(env_season$P~env_season$Poligono)
k.p.s
k.p.p


all.kw<- data.frame(pH=c(k.ph.s,k.ph.p),
                    OM=c(k.mo.s, k.mo.p),
                    N=c(k.n.s, k.n.p),
                    P=c(k.p.s, k.p.p))
rownames(all.kw)<-c("Season", "Poligon")

#write.csv(all.kw,"oldies/Data/all.kw.csv")
```


```{r, message=FALSE, warning=FALSE}
#linear models and normality and heterogenity test
model1<- lm(pH ~ Poligono*Season, data = env_season)
car::leveneTest(pH ~ Poligono*Season, data = env_season)
plot(model1, which = 2)

model2<- lm(MO ~ Poligono*Season, data = env_season)
car::leveneTest(MO ~ Poligono*Season, data = env_season)
plot(model2, which = 2)

model3<- lm(N ~ Poligono*Season, data = env_season)
car::leveneTest(N ~ Poligono*Season, data = env_season)
plot(model3, which = 2)

model4<- lm(P ~ Poligono*Season, data = env_season)
car::leveneTest(P ~ Poligono*Season, data = env_season)
plot(model4, which = 2)
```


```{r, message=FALSE, warning=FALSE}
#linear models for test with interaction

library(tidyverse)

lm.ph<-lm(pH~Season*Poligono ,data = env_season)
lm.ph.perm<-summary(aov(lm.ph))
lm.ph.perm<- lm.ph.perm[[1]][5] %>%as.data.frame() %>%  slice(1:3) %>% mutate_if(is.numeric, ~round(.,digits = 3))
lm.ph.perm

lm.mo<-lm(MO~Season*Poligono ,data = env_season)
lm.mo.perm<-summary(aov(lm.mo))
lm.mo.perm<-lm.mo.perm[[1]][5] %>%as.data.frame() %>%  slice(1:3) %>% mutate_if(is.numeric, ~round(.,digits = 3))
lm.mo.perm


lm.n<-glm(N~Season*Poligono ,data = env_season, family=Gamma(link = "identity"))
lm.n.perm<-summary(aov(lm.n))
lm.n.perm<- lm.n.perm[[1]][5] %>%as.data.frame() %>%  slice(1:3) %>% mutate_if(is.numeric, ~round(.,digits = 3))
lm.n.perm


lm.p<-lm(P~Season*Poligono ,data = env_season,family=Gamma(link = "identity"))
lm.p.perm<-summary(aov(lm.p))
lm.p.perm<- lm.p.perm[[1]][5] %>%as.data.frame() %>%  slice(1:3) %>% mutate_if(is.numeric, ~round(.,digits = 3))
lm.p.perm


all.lm<- cbind(lm.ph.perm, lm.mo.perm, lm.n.perm, lm.p.perm)
colnames(all.lm)<-c("pH", "MO", "N", "P")



write.csv(all.lm,"../Data/all.lm.csv")



```

```{r, eval=FALSE, echo=FALSE}
# letters of interaction

model1.1<- lm(pH~interact, data = env_season)
model2.1<- lm(MO ~ interact, data = env_season)
model3.1<- lm(N ~ interact, data = env_season)
model4.1<- lm(P ~ interact, data = env_season)


agricolae::HSD.test(model1.1, trt ="interact", console = TRUE)
emmeans2<- emmeans::emmeans(model2.1, pairwise ~ interact)
multcomp::cld(object = emmeans2$emmeans, Letters=letters)

emmeans3<- emmeans::emmeans(model3.1, pairwise ~ interact)
multcomp::cld(object = emmeans3$emmeans, Letters=letters)


emmeans4<- emmeans::emmeans(model4.1, pairwise ~ interact)
multcomp::cld(object = emmeans4$emmeans, Letters=letters)


```


```{r, message=FALSE, warning=FALSE}
# Plot the temporal trends of the selected environmental variables over time
df$Season<-NA
df$Season<-env_season$Season
df$Season = factor(df$Season, levels = c("Dry", "Wet"), labels = c("Dry", "Rainy"))
melted_df=melt(df, id=c("Poligono", "Season"))

mean=Rmisc::summarySE(melted_df, measurevar = "value", groupvars=c("Poligono","variable", "Season"), na.rm = T)
mean$variable=factor(mean$variable, levels = c("pH", "MO", "N", "P"))

conservation_status <- c(
  pH = "pH",
 MO = "OM (%)",
  N = "N (mg/Kg)",
  P= "P (mg/Kg)")

library(plyr)
mean$conservation2 <- plyr::revalue(mean$variable, conservation_status)
melted_df$conservation2 <- plyr::revalue(melted_df$variable, conservation_status)

labels <- all.lm %>%  t()  %>% 
  as.data.frame() %>%
  mutate(letter= c("A", "B", "C", "D"))  %>%
 rownames_to_column(var = "variable") %>%
  mutate(`Poligono       `=case_when(
    `Poligono       `==0 ~ "0.000",
    TRUE ~ as.character(`Poligono       `))) %>%
  mutate(`Season         `=case_when(
   `Season         `==0 ~ "0.000" ,
    TRUE ~ as.character(`Season         `))) %>% 
  mutate(labels = paste0(letter, "       Season = ",`Season         `, ", Polygon = ", `Poligono       `, ", Season:Polygon = ", signif(`Season:Poligono`, digits = 3)))


#labels <- labels %>% rownames_to_column(var = "conservation2")
labels$conservation2<-factor(labels$variable, levels = c("pH",  "MO",  "N", "P"), labels =c("pH",  "OM (%)",  "N (mg/Kg)", "P (mg/Kg)") )
labels<- labels %>% mutate(Poligono="P6") %>% mutate(value=c(7.5,25,130,80))


fq<-ggline(melted_df, x="Poligono", y="value", shape = "Season", 
       linetype="Season", facet.by = "conservation2", add = "mean_sd")+
  facet_grid(conservation2~., scales = "free_y")+labs(x="Polygon",y="Mean±SD")+
  theme_grey()+
    theme(legend.position="right")+
  theme(axis.text = element_text(size=12),
        axis.title =  element_text(size=14),
        strip.text = element_text(size=12),
        plot.title = element_text(size=8, face="bold")  )+
  geom_text(data = labels, aes(label=labels),
            fontface="bold",
                hjust = 1, vjust = 1)+ theme(
                  strip.background = element_rect(
     color="black", fill="black", size=1.5, linetype="solid"),
     strip.text = element_text(colour = "white", face = "bold"))
fq

ggsave('../Plots/fisico-season-mod.png', width =7, height = 8, dpi = 300, plot =fq)
#quartz.save("meanplot.pdf", type = "pdf") 
#quartz.save("meanplot.tiff", type = "tiff")

```



