---
title: "Polygon turnover "
output: html_document
date: "2024-07-03"
---
# spatial turnover

```{r}
# TURNOVER  SPATIAL

library(qiime2R)
library(tidyverse)
library(ggpubr)
library(hilldiv)

table<- read_qza("../Data/table_SMOQ_rar.qza")$data
metadata<- read.delim("../Data/its_map.txt")

#convert data to incidence
presabs<- function(x){x[x>0]=1 
return(t(x))}
tables_presabs<- presabs(table)
table_presabs<- tables_presabs %>% as.data.frame() %>% rownames_to_column(var = "SampleID") %>%   arrange(SampleID) %>% column_to_rownames(var = "SampleID")


```


```{r}
library(betapart)
library(vegan)
#betapart function with jaccard 
x<- beta.pair(table_presabs, index.family = "jaccard")
jac<- x$beta.jac
jtu<- x$beta.jtu
jne<- x$beta.jne


```




```{r}
resultado <- metaMDS(jtu, k = 2)

nmds_data <- data.frame(
  NMDS1 = resultado$points[, 1],  
  NMDS2 = resultado$points[, 2] )


source("../Scripts/gg_ordiplots4.R")

metadata1 <- metadata[match(colnames(as.matrix(jtu)), metadata$SampleID),]

nmds_data_metadata<- nmds_data %>% rownames_to_column(var = "SampleID") %>%
  inner_join(metadata) %>% column_to_rownames(var = "SampleID")# %>% filter(Season=="Dry")


nmds_data_metadata_dry<- nmds_data %>% rownames_to_column(var = "SampleID") %>%
  inner_join(metadata) %>% column_to_rownames(var = "SampleID") %>% filter(Season=="Dry")

nmds_data_metadata_rainy<- nmds_data %>% rownames_to_column(var = "SampleID") %>%
  inner_join(metadata) %>% column_to_rownames(var = "SampleID") %>% filter(Season=="Rainy")

y1<-gg_ordiplot4(nmds_data_metadata, groups = nmds_data_metadata$Poligono, groups2 = nmds_data_metadata$Season, spiders = T, plot = F, scaling = 3)

y2<-gg_ordiplot4(nmds_data_metadata_dry, groups = nmds_data_metadata_dry$Poligono, groups2 = nmds_data_metadata_dry$Season, spiders = T, plot = F, scaling = 3)

y3<-gg_ordiplot4(nmds_data_metadata_rainy, groups = nmds_data_metadata_rainy$Poligono, groups2 = nmds_data_metadata_rainy$Season, spiders = T, plot = F, scaling = 3)

#xlab <- y1$plot$labels$x
#ylab <- y1$plot$labels$y

z1<-ggplot()+ geom_point(data = y1$df_ord %>% rownames_to_column(var="SampleID") %>%
                          inner_join(metadata1),
                        aes(x = x*-1, y = y*-1, color = Group, shape=Season), size = 3) +
  xlab("NMDS1") +
  ylab("NMDS2")+
  geom_segment(data = y1$df_spiders,
               aes(x = cntr.x*-1, xend = x*-1, y = cntr.y*-1, yend = y*-1, color = Group),
               show.legend = FALSE)+
  
  guides(
    color=guide_legend(title="Sites"))+theme_linedraw() +
  geom_vline(xintercept = 0, linetype = 2) +   #lines-cross
  geom_hline(yintercept = 0, linetype = 2) +
  theme_linedraw()+
  #scale_fill_viridis_d(option ="turbo", name="Poligono")+#color of points
    scale_color_carto_d(name = "Polygons", palette = "Safe") +
  theme_grey()+#color of points
  theme(axis.text = element_text(colour = "black", size = 12),
        axis.title = element_text(colour = "black", size = 12),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        
        legend.position = "right",
        legend.box = "vertical",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(color = "black")) +
  scale_shape_manual(values = c(16,17))
     

z2<-ggplot()+ geom_point(data = y2$df_ord %>% rownames_to_column(var="SampleID") %>%
                          inner_join(metadata1),
                        aes(x = x*-1, y = y*-1, color = Group, shape=Season), size = 3) +
  xlab("NMDS1") +
  ylab("NMDS2")+
  geom_segment(data = y2$df_spiders,
               aes(x = cntr.x*-1, xend = x*-1, y = cntr.y*-1, yend = y*-1, color = Group),
               show.legend = FALSE)+
  
  guides(
    color=guide_legend(title="Sites"))+theme_linedraw() +
  geom_vline(xintercept = 0, linetype = 2) +   #lines-cross
  geom_hline(yintercept = 0, linetype = 2) +
  theme_linedraw()+
  #scale_fill_viridis_d(option ="turbo", name="Poligono")+#color of points
    scale_color_carto_d(name = "Polygons", palette = "Safe") +
  theme_grey()+#color of points
  theme(axis.text = element_text(colour = "black", size = 12),
        axis.title = element_text(colour = "black", size = 12),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        
        legend.position = "right",
        legend.box = "vertical",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(color = "black")) +
  scale_shape_manual(values = c(16,17))
     
z3<-ggplot()+ geom_point(data = y3$df_ord %>% rownames_to_column(var="SampleID") %>%
                          inner_join(metadata1),
                        aes(x = x*-1, y = y*-1, color = Group, shape=Season), size = 3) +
  xlab("NMDS1") +
  ylab("NMDS2")+
  geom_segment(data = y3$df_spiders,
               aes(x = cntr.x*-1, xend = x*-1, y = cntr.y*-1, yend = y*-1, color = Group),
               show.legend = FALSE)+
  
  guides(
    color=guide_legend(title="Sites"))+theme_linedraw() +
  geom_vline(xintercept = 0, linetype = 2) +   #lines-cross
  geom_hline(yintercept = 0, linetype = 2) +
  theme_linedraw()+
  #scale_fill_viridis_d(option ="turbo", name="Poligono")+#color of points
    scale_color_carto_d(name = "Polygons", palette = "Safe") +
  theme_grey()+#color of points
  theme(axis.text = element_text(colour = "black", size = 12),
        axis.title = element_text(colour = "black", size = 12),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 12),
        
        legend.position = "right",
        legend.box = "vertical",
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(color = "black")) +
  scale_shape_manual(values = c(17,16))
     

```

```{r}
#dendograms

library(usedist)
library(ggdendro)
source("../Scripts/ggdendro_funct.R")

dry_ids=metadata1 %>% filter(Season=="Dry") %>% dplyr::select(SampleID)
rainy_ids=metadata1 %>% filter(Season=="Rainy") %>% dplyr::select(SampleID)
jtu2 <- dist_subset(jtu, dry_ids$SampleID)
jtu3 <- dist_subset(jtu, rainy_ids$SampleID)

dendrogram <- hclust(as.dist(jtu), method='ward.D2')
dendrogram2 <- hclust(as.dist(jtu2), method='ward.D2')
dendrogram3 <- hclust(as.dist(jtu3), method='ward.D2')

hcdata <- dendro_data_k(dendrogram, 2)
hcdata2 <- dendro_data_k(dendrogram2, 2)
hcdata3 <- dendro_data_k(dendrogram3, 2)


clusters <- dendrogram
clusters$labels
clusters=clusters$labels[clusters$order]
table_all = table[,match(clusters, colnames(table))]
table_all=table_all %>% t() %>% as.data.frame() %>%  
  rownames_to_column(var = "SampleID") %>% inner_join(metadata)

clusters2 <- dendrogram2
clusters2$labels
clusters2=clusters2$labels[clusters2$order]
table_dry = table[,match(clusters2, colnames(table))]
table_dry=table_dry %>% t() %>% as.data.frame() %>%  
  rownames_to_column(var = "SampleID") %>% inner_join(metadata) %>% filter(Season=="Dry")


clusters3 <- dendrogram3
clusters3$labels
clusters3=clusters3$labels[clusters3$order]
table_rainy = table[,match(clusters3, colnames(table))]
table_rainy=table_rainy %>% t() %>% as.data.frame() %>%  
  rownames_to_column(var = "SampleID") %>% inner_join(metadata)%>% filter(Season=="Rainy")


cols <- c("#2E86C1", "#800080","#30123BFF", "#3E9BFEFF", "#46F884FF", "#E1DD37FF", "#F05B12FF", "#7A0403FF")

p <- plot_ggdendro(hcdata,
                   direction   = "tb",
                  scale.color = cols,
                   label.size  = 2,
                   branch.size = 0.5,
                   expand.y    = 0.2)

 p=p + theme_void() + expand_limits(x = c(-1, 32))+
  geom_point(data     = table_all, 
             aes(x    = match(table_all$SampleID, hcdata$labels$label),
                 y    = -0.5,
                 fill = as.factor(Poligono),
                 shape= as.factor(Season)),
                 size = 4,
             
             show.legend = FALSE) +
    scale_fill_carto_d(name = "Polygons", palette = "Safe") +
   scale_shape_manual(values = c(21,24))

p2 <- plot_ggdendro(hcdata2,
                   direction   = "tb",
                  scale.color = cols,
                   label.size  = 3,
                   branch.size = 0.5,
                   expand.y    = 0.2)

 p2=p2 + theme_void() + expand_limits(x = c(-1, 32))+
  geom_point(data     = table_dry, 
             aes(x    = match(table_dry$SampleID, hcdata2$labels$label),
                 y    = -0.5,
                 fill = as.factor(Poligono),
                 shape= as.factor(Season)),
                 size = 4,
             
             show.legend = FALSE) +
    scale_fill_carto_d(name = "Polygons", palette = "Safe") +
   scale_shape_manual(values = c(21,24))

p3 <- plot_ggdendro(hcdata3,
                   direction   = "tb",
                  scale.color = c("#800080","#2E86C1"),
                   label.size  = 3,
                   branch.size = 0.5,
                   expand.y    = 0.2)

p3=p3 + theme_void() + expand_limits(x = c(-1, 32))+
  geom_point(data     = table_rainy, 
             aes(x    = match(table_rainy$SampleID, hcdata3$labels$label),
                 y    = -0.5,
                 fill = as.factor(Poligono),
                 shape= as.factor(Season)),
                 size = 4,
             
             show.legend = FALSE) +
    scale_fill_carto_d(name = "Polygons", palette = "Safe") +
   scale_shape_manual(values = c(24,21))
 

```

```{r}
z1a = z1+ guides(colour = guide_legend(nrow = 1, title = "Polygon"),
                          shape = guide_legend(nrow = 1) )+
  theme(legend.position = "top",  legend.box = "horizontal")
leg<- get_legend(z1a)

library(cowplot)            

dendos=plot_grid(p2+theme(legend.position = "none"),
                 p3+theme(legend.position = "none"), 
                 p+theme(legend.position = "none"),
                 rel_widths = c(1,1,1.5),labels = c("A", "B", "C"),
                 nrow = 1)

ndmss=plot_grid( z2+theme(legend.position = "none"),
            z3+theme(legend.position = "none"),
            z1+theme(legend.position = "none") ,
          nrow = 1, rel_widths = c(1,1,1.5))

all = plot_grid(dendos,ndmss, nrow = 2, rel_heights = c(0.3,1))
all2 = plot_grid(leg, all, nrow = 2, rel_heights = c(0.1,1))

ggsave('../Plots/spatial_turnover_jaccard.jpg', width =19, height = 8, dpi = 300, plot =all2)

```

