---
title: "heatmap"
output: html_document
date: "2024-06-03"
---

- Load data and packages and format

```{r}
library(tidyverse)
library(qiime2R)
library(ComplexHeatmap)
library(circlize)
library(viridis)
library(ggh4x)

tab <- read_qza("../Data/table_SMOQ.qza")$data %>% as.data.frame() %>% 
rownames_to_column(var = "Feature.ID") 
taxa<- qiime2R::read_qza("../Data/taxonomy_SMOQ_ver10.qza")$data %>% as.data.frame()

#tab <- read_qza("../Data/table_SMDR.qza")$data %>% as.data.frame() %>% 
#rownames_to_column(var = "Feature.ID") 
#taxa<- qiime2R::read_qza("../Data/taxonomy_SMDR.qza")$data %>% as.data.frame()


tab_tax<- tab %>% inner_join(taxa)

tab_taxa<- tab_tax %>% dplyr::select(OTUID=Feature.ID, `121D`:`221D`, taxonomy=Taxon)
#tab_taxa<- tab_tax %>% dplyr::select(OTUID=Feature.ID, `111D`:`623R`, taxonomy=Taxon)


#guilds

#guild1<- read.delim("../Data/otus/table_otus.guilds_matched.txt", check.names = F) %>% 
 # filter(!"Trophic Mode"=="na") %>%
  #mutate(Guild = str_replace_all(Guild, "\\|", ""))

guild1<- read.delim("../Data/asvs/table_asvs.guilds_matched.txt", check.names = F) %>% 
 filter(!"Trophic Mode"=="na") %>%
mutate(Guild = str_replace_all(Guild, "\\|", ""))



guild<- guild1 %>% group_by(Guild) %>% summarise_if(is.numeric, sum)
trophic<- guild1 %>% group_by(`Trophic Mode`) %>% summarise_if(is.numeric, sum)


relabunda<- function(x){(as.data.frame(t(t(x)/colSums(x)))*100)}

metadata<- read.delim("../Data/its_map.txt")


vector_order<- c("111D" , "112D", "113D" ,"121D", "122D" ,"123D", "111R" ,"112R", "113R", "121R", "122R" ,"123R",
                 "211D" ,"212D" ,"213D" ,"221D" ,"222D" ,"223D", "211R" ,"212R" ,"213R", "221R", "222R" ,"223R",
                 "311D" ,"312D" ,"313D" ,"321D", "323D" ,"322D","311R" ,"312R" ,"313R" ,"321R", "322R" ,"323R" ,
                 "411D" ,"412D" ,"413D" ,"421D" ,"422D" ,"423D", "411R", "412R" ,"413R" ,"421R" ,"422R" ,"423R",
                 "511D" ,"512D" ,"513D" ,"521D" ,"522D", "523D", "511R", "512R" ,"513R" ,"521R", "522R" ,"523R",
                 "611D" ,"612D" ,"613D", "621D" ,"622D", "623D",  "611R", "612R","613R", "621R" ,"622R", "623R")

#ordering

#taxones_color<- read_csv("../Data/taxones_color.csv") %>% dplyr::rename(Genus=Taxon)


table_genus <- tab_taxa %>%  separate(taxonomy,
                                      c(
                                        "Kingdom",
                                        "Phylum",
                                        "Order",
                                        "Class",
                                        "Family",
                                        "Genus",
                                        "Species"
                                      ),
                                      sep = ";") %>% mutate_at(c("Genus"), ~ str_replace(., "g__", "")) %>%
  dplyr::mutate(Genus = stringr::str_trim(Genus, side = "both")) %>% mutate_if(is.character, ~
                                                                                 replace_na(., "Unassigned")) %>% group_by(Genus) %>% summarise_if(is.numeric, sum) %>%
  column_to_rownames(var = "Genus") %>% t() %>% as.data.frame() %>%
  rownames_to_column(var = "SampleID") %>%
  inner_join(metadata) %>% group_by(Poligono, Season) %>%
  summarise_if(is.numeric, sum) %>%
  unite("ids", Poligono:Season, sep = "_") %>% column_to_rownames(var = "ids") %>%
  t() %>% as.data.frame() %>% mutate(all = rowSums(.)) %>% dplyr::arrange(-all) %>% relabunda(.) %>%
  as.data.frame() %>%  rownames_to_column(var = "Genus") %>% filter(!Genus ==
                                                                      "unidentified" ,
                                                                    !Genus == "Unassigned") %>%
  filter(!grepl('Incertae_sedis', Genus)) %>% slice(c(1:50))  %>% pivot_longer(.,
                                                                               cols = -Genus,
                                                                               names_to = "SampleID",
                                                                               values_to = "relab") %>% filter(!SampleID ==
                                                                                                                 "all")


gen_sum_all = table_genus %>% pivot_wider(names_from = "Genus", values_from = "relab") %>% 
  column_to_rownames(var = "SampleID") %>% 
  t() %>% as.data.frame() %>%
  mutate(proms = rowMeans(select(., where(is.numeric)), na.rm = TRUE)) %>% 
  arrange(-proms)  %>%
  rownames_to_column(var = "Genus") %>% 
  rowwise() %>%
  mutate(sd_value = sd(c_across(where(is.numeric)), na.rm = TRUE)) %>%
  ungroup()


gen_sum_pol = table_genus %>% pivot_wider(names_from = "Genus", values_from = "relab") %>% 
  separate(SampleID, into = c("pol", "Season")) %>% group_by(pol) %>% 
  summarise_if(is.numeric, mean) %>% 
  column_to_rownames(var = "pol") %>% 
  t() %>% as.data.frame() %>%
  mutate(proms = rowMeans(select(., where(is.numeric)), na.rm = TRUE)) %>% 
  arrange(-proms)  %>%
  rownames_to_column(var = "Genus") %>% 
  rowwise() %>%
  mutate(sd_value = sd(c_across(where(is.numeric)), na.rm = TRUE)) %>%
  ungroup()
gen_sum_pol_sd = table_genus %>% pivot_wider(names_from = "Genus", values_from = "relab") %>% 
  separate(SampleID, into = c("pol", "Season")) %>% group_by(pol) %>% 
  summarise_if(is.numeric, sd) %>% 
  column_to_rownames(var = "pol") %>% 
  t() %>% as.data.frame() %>%
  mutate(proms = rowMeans(select(., where(is.numeric)), na.rm = TRUE)) %>% 
  arrange(-proms)  %>%
  rownames_to_column(var = "Genus") %>% 
  rowwise() %>%
  mutate(sd_value = sd(c_across(where(is.numeric)), na.rm = TRUE)) %>%
  ungroup()


```


```{r}
guilds = guild %>% column_to_rownames(var = "Guild") %>% relabunda() %>%
  mutate(proms = rowMeans(select(., where(is.numeric)), na.rm = TRUE)) %>% 
  arrange(-proms)  %>%
  rownames_to_column(var = "Genus") %>% 
  rowwise() %>%
  mutate(sd_value = sd(c_across(where(is.numeric)), na.rm = TRUE)) %>%
  ungroup()

trophics = trophic %>% column_to_rownames(var = "Trophic Mode") %>% relabunda() %>%
  mutate(proms = rowMeans(select(., where(is.numeric)), na.rm = TRUE)) %>% 
  arrange(-proms)  %>%
  rownames_to_column(var = "Genus") %>% 
  rowwise() %>%
  mutate(sd_value = sd(c_across(where(is.numeric)), na.rm = TRUE)) %>%
  ungroup()

table_phyl <- tab_taxa %>%  separate(taxonomy,
                                      c(
                                        "Kingdom",
                                        "Phylum",
                                        "Order",
                                        "Class",
                                        "Family",
                                        "Genus",
                                        "Species"
                                      ),
                                      sep = ";")  %>% group_by(Phylum) %>%
  summarise_if(is.numeric, sum) %>% drop_na() %>% column_to_rownames(var = "Phylum") %>% relabunda() %>%
  mutate(proms = rowMeans(select(., where(is.numeric)), na.rm = TRUE)) %>% 
  arrange(-proms)  %>%
  rownames_to_column(var = "Genus") %>% 
  rowwise() %>%
  mutate(sd_value = sd(c_across(where(is.numeric)), na.rm = TRUE)) %>%
  ungroup()

```

