---
title: "Seasonal turnover"
output: html_document
date: "2024-06-07"
---

```{r}
#beta
library(tidyverse)
library(betapart)
library(qiime2R)
library(vegan)
library(colorRamps)
library(ggpubr)
library(ggordiplots)

table<- read_qza("../Data/table_SMOQ_rar.qza")$data

metadata<- read.delim("../Data/its_map.txt")


#convrt data
presabs<- function(x){x[x>0]=1 
return(t(x))}
tables_presabs<- presabs(table)
table_presabs<- tables_presabs %>% as.data.frame() %>% rownames_to_column(var = "SampleID") %>% 
  arrange(SampleID) %>% column_to_rownames(var = "SampleID")
```


```{r}
#betapart season

nam<- colnames(table)
nam2<- str_extract(nam, pattern = "^\\d+")
nam3<- unique(nam2)

drys<- paste0(nam3,"D")
rainys<- paste0(nam3,"R")

tables_dry<- table_presabs %>% as.data.frame() %>%rownames_to_column(var="SampleID") %>% 
  filter(SampleID %in% drys) %>% mutate(SampleID = str_extract(SampleID, "^\\d+")) %>% 
  column_to_rownames(var = "SampleID") 

tables_rainy<- table_presabs  %>% as.data.frame() %>%rownames_to_column(var="SampleID") %>% 
  filter(SampleID %in% rainys) %>% mutate(SampleID = str_extract(SampleID, "^\\d+")) %>% 
  column_to_rownames(var = "SampleID") 


beta.t <-beta.temp(tables_dry, tables_rainy,index.family="jaccard")


nams<-paste0(rownames(beta.t), "D")


table_jac<-rbind(beta.t[[3]])
colnames(table_jac)<-nams

table_turn<-rbind(beta.t[[1]]) 
colnames(table_turn)<-nams

table_nes<-rbind(beta.t[[2]])
colnames(table_nes)<-nams


table_jacs<- table_jac %>%t() %>% as.data.frame() %>% 
  rownames_to_column(var = "SampleID") %>% inner_join(metadata) %>% 
  dplyr::rename(beta=V1)

table_turns<- table_turn %>%t() %>% as.data.frame() %>% 
  rownames_to_column(var = "SampleID") %>% inner_join(metadata) %>% 
  dplyr::rename(beta=V1)

table_ness<- table_nes %>%t() %>% as.data.frame() %>% 
  rownames_to_column(var = "SampleID") %>% inner_join(metadata) %>% 
  dplyr::rename(beta=V1)

model<-aov(beta~Poligono, data=table_turns)
out <- agricolae::HSD.test(model,"Poligono", group=TRUE,console=FALSE)
g<- data.frame(out$groups) %>% rownames_to_column(var = "Poligono") %>% dplyr::select(-beta)
data<- data.frame(Poligono=c("P1", "P2", "P3", "P4", "P5", "P6"),
                  beta=rep(0.85,6)) %>% inner_join(g, by = "Poligono")
library(ggpubr)
t<-ggboxplot(data = table_turns, x = "Poligono", y="beta", fill="Poligono")+
    scale_fill_carto_d(name = "Polygons ", palette = "Safe") +
  theme_grey() +theme(axis.text = element_text(colour = "black", size = 14),
                     axis.title = element_text(colour = "black", size = 16),
                     legend.text = element_text(size = 10),
                     legend.title = element_text(size = 12), 
                     legend.position = "right", 
                     legend.box = "vertical",
                     axis.text.x = element_blank(),
                     axis.ticks.x = element_blank(),
                     panel.border = element_rect(colour = "black", fill=NA, size=1,))+
  ylab("Temporal turnonver of Jaccard dissimilarity")+
  xlab("Polygon")+
  stat_compare_means(method = "anova", label.y = 0.86, size=5)+
  geom_label(data = data,aes(Poligono, beta, label=groups), size=5)+
  stat_summary(fun.y=mean, geom="point", shape=23, size=4, color="black", fill="white")
  
t
ggsave('../Plots/temporal_turnover_jaccard.png', width =8, height = 6, dpi = 300, plot =t)

```

