---
title: "Figure 2"
author:
- name: Stephanie Hereira
  affiliation: Universidad Autónoma de Tlaxcala
  email: sehereirap@uatx.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: flatly
    highlight: kate
    toc: yes
    toc_depth: 2
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '2'
---

## Figure 2: Heatmap

- Load packages and data
```{r, warning=FALSE, message=FALSE}
library(vegan)
library(qiime2R)
library(readxl)
library(tidyverse)
library(ggh4x)
library(ComplexHeatmap)
library(circlize)
library(viridis)
source("~/Documents/2023/corredor_scripts/Fungal_Communities_PNIP_PNML/Code/general_functions.R")
metadata<-read.delim("Data/its_map.txt") %>% mutate_if(is.numeric, as.factor)
meta<-metadata
table_oc<-read_qza("Data/table_oc.qza")$data
table_oim<- read_qza("Data/table_oim.qza")$data %>% t() %>% 
  as.data.frame() %>% rownames_to_column(var = "ids") %>% 
  mutate(ids=str_extract(ids, "^\\w..[^_]")) %>% 
  column_to_rownames(var = "ids") %>% t()
table_oism<- read_qza("Data/table_oism.qza")$data  %>% t() %>% 
  as.data.frame() %>% rownames_to_column(var = "ids") %>% 
  mutate(ids=str_extract(ids, "[^_]+(?=_................\\w[^_]*$)")) %>% 
  column_to_rownames(var = "ids") %>% t()
table_ojis<- read_qza("Data/table_ojis.qza")$data %>% t() %>% 
  as.data.frame() %>% rownames_to_column(var = "ids") %>% 
  mutate(ids=str_extract(ids, "[^_]+(?=_............\\w[^_]*$)")) %>% 
  column_to_rownames(var = "ids") %>% t()
table_oiss<- read_qza("Data/table_oiss.qza")$data%>% t() %>% 
  as.data.frame() %>% rownames_to_column(var = "ids") %>% 
  mutate(ids=str_extract(ids, "[^_]+(?=................\\w[^_]*$)")) %>% 
  column_to_rownames(var = "ids") %>% t()
table_ac<- read_qza("Data/table_ac.qza")$data
table_aism<- read_qza("Data/table_aism.qza")$data
table_aisc<- read_qza("Data/table_aisc.qza")$data
table_ajis<- read_qza("Data/table_ajis.qza")$data

taxa_oc<- read_qza("Data/taxonomy_oc.qza")$data
taxa_oim<- read_qza("Data/taxonomy_oim.qza")$data
taxa_oism<- read_qza("Data/taxonomy_oism.qza")$data
taxa_ojis<- read_qza("Data/taxonomy_ojis.qza")$data
taxa_oiss<- read_qza("Data/taxonomy_oiss.qza")$data
taxa_ac<- read_qza("Data/taxonomy_sklearn_ac.qza")$data
taxa_aism<- read_qza("Data/taxonomy_sklearn_aism.qza")$data
taxa_aisc<- read_qza("Data/taxonomy_sklearn_aisc.qza")$data
taxa_ajis<- read_qza("Data/taxonomy_ajis.qza")$data


table_oim<- table_oim[,match(colnames(table_oc), colnames(table_oim))]
table_oism<- table_oism[,match(colnames(table_oc), colnames(table_oism))]
table_ojis<- table_ojis[,match(colnames(table_oc), colnames(table_ojis))]
table_oiss<- table_oiss[,match(colnames(table_oc), colnames(table_oiss))]

table_ac<- table_ac[,match(colnames(table_oc), colnames(table_ac))]
table_aism <- table_aism[,match(colnames(table_oc), colnames(table_aism))]
table_aisc <- table_aisc[,match(colnames(table_oc), colnames(table_aisc))]
table_ajis <- table_ajis[,match(colnames(table_oc), colnames(table_ajis))]


list_table<- list(table_oc, table_oim, table_oism, table_ojis, table_oiss,
                  table_ac, table_aism, table_aisc, table_ajis)
names(list_table)<- c("OC", "OIM", "OISM", "OJIS", "OISS",
                      "AC", "AISM", "AISC", "AJIS")
list_taxa<- list(taxa_oc, taxa_oim, taxa_oism, taxa_ojis,
                 taxa_oiss, taxa_ac, taxa_aism, taxa_aisc, taxa_ajis)


names(list_taxa)<- c("OC", "OIM", "OISM", "OJIS", "OISS",
                     "AC", "AISM", "AISC", "AJIS")


```

- Formatting data for Heatmap
```{r, warning=FALSE, message=FALSE}
taxones_color<- read_csv("Data/colors.csv")

data_fun<- function(tab, taxonomy, metadata){
  table_genus<- tab %>%as.data.frame() %>% rownames_to_column(
    var = "Feature.ID") %>%  inner_join(taxonomy) %>% separate(
      Taxon, c("k","p","c","o","f","g","s"), sep = ";" ) %>% mutate_at(
        c("g"), ~str_replace(., "g__", ""))%>% 
    dplyr::mutate(g = stringr::str_trim(g, side = "both")) %>% mutate_if(
      is.character, ~replace_na(., "Unassigned")) %>% group_by(
        g) %>% summarise_if(is.numeric, sum) %>% column_to_rownames(
          var = "g") %>%  mutate(
            all= rowSums(.)) %>% dplyr::arrange(
              -all) %>% rel_ab(.) %>%as.data.frame( ) %>%  rownames_to_column(
              var = "Taxon")%>% filter(!Taxon=="unidentified" ,
                                       !Taxon=="Unassigned") %>% slice(
                                         c(1:50))  %>% pivot_longer(
                                           ., cols = -Taxon, 
                                           names_to ="SampleID", 
                                           values_to = "relab" ) %>% filter( !SampleID=="all")

table_genus2<- table_genus %>% inner_join(metadata) %>% 
  group_by(Taxon,Poligono) %>% summarise_if(is.numeric, mean)

cols<- table_genus2  %>%  inner_join(taxones_color) %>% arrange(Taxon)
col <- as.character(cols$color)
names(col) <- as.character(cols$Taxon)
  
barplot_genus<- table_genus2%>% pivot_wider(
      names_from = Taxon, values_from = relab) %>% column_to_rownames(
        var = "Poligono") %>% t() %>% as.data.frame()
}

data_oc<- data_fun(table_oc, taxa_oc, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_OC"))%>% rownames_to_column(var="gen")

data_oim<- data_fun(table_oim, taxa_oim, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_OIM"))%>% rownames_to_column(var="gen")

data_oism<- data_fun(table_oism, taxa_oism, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_OISM"))%>% rownames_to_column(var="gen")

data_ojis<- data_fun(table_ojis, taxa_ojis, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_OJIS"))%>% rownames_to_column(var="gen")

data_oiss<- data_fun(table_oiss, taxa_oiss, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_OISS"))%>% rownames_to_column(var="gen")


data_ac<- data_fun(table_ac, taxa_ac, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_AC"))%>% rownames_to_column(var="gen")

data_aism<- data_fun(table_aism, taxa_aism, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_AIM"))%>% rownames_to_column(var="gen")

data_aisc<- data_fun(table_aisc, taxa_aisc, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_AISC"))%>% rownames_to_column(var="gen")

data_ajis<- data_fun(table_ajis, taxa_ajis, metadata) %>%
  rename_if(is.numeric, ~paste0(.,"_AJIS"))%>% rownames_to_column(var="gen")

merge_data<- data_oc%>% full_join(
  data_oim)%>% full_join(
    data_oism)%>% full_join(
      data_ojis) %>% full_join(
        data_oiss) %>% full_join(
          data_ac) %>% full_join(
            data_aism) %>% full_join(
              data_aisc) %>% full_join(
                data_ajis  ) %>%   replace(is.na(.), 0)  %>% 
  filter(!str_detect(gen, 'gen_Incertae_sedis'))%>% column_to_rownames(
        var = "gen") %>% mutate(proms=rowMeans(.)) %>% arrange(-proms) %>% slice(
          1:60)%>% dplyr::select(-proms) %>% mutate_all(., funs(R = case_when(
          . <= 0.001 ~ 0,
          . >  0.001 & .  <= 0.005 ~ 1,
          . >  0.005 & .  <= 0.01 ~ 2,
          . >  0.01 & .  <= 0.10 ~ 3,
          . >  0.10 & .  <= 0.20 ~ 4,
          . >  0.20 & .  <= 1.00 ~ 5,
          . >  1.00 & .  <= 2.00 ~ 6,
          . >  2.00 & .  <= 5.00 ~ 7,
          . >  5.00 & .  <= 10.00 ~ 8,
          . >  10.00 & .  <= 25.00 ~ 9,
          . >  25.00 & .  <= 50.00 ~ 10,
          . >  50.00 & .  <= 75.00 ~ 11,
          . >  75.00 ~ 12))) %>%select_at(
            vars(contains("_R"))) %>% select_all(~str_replace(., "_R", ""))
```

- Setting annotations and format for Heatmap
```{r, warning=FALSE, message=FALSE}
col_fun2 = colorRamp2(c(0,  1, 1+1e-5,10,50, 100), 
                      viridis(6, option = "F", direction = -1))
my_palette <- viridis::viridis(n = 12, option = "F", direction = -1)
col_fun = colorRamp2(c(0,  1, 1+1e-5,5,5+1e-5,10,10+1e-5,50,50+1e-5, 75, 75+1e-5,100), 
                      viridis(12, option = "F", direction = -1))

#annotation ids
annotation_columns<- data.frame(id=colnames(merge_data)) 
rownames(annotation_columns) <- colnames(merge_data)

#set.seed(123)
split = rep(1:9, each = 6)


ha = HeatmapAnnotation("Method" = anno_block(gp = gpar(
  fill = c("black" ,"black" ,"black", "black")), 
  labels = names(list_table), 
  labels_gp = gpar(col = "white", fontsize = 9, fontface= "bold")))

Pol<- c(1:6)

cols_ho<- list("Pol" = c("1"="#30123BFF",
                           "2"= "#4490FEFF",
                           "3"= "#29EFA2FF",
                           "4"="#C1F334FF",
                           "5"= "#FE922AFF",
                           "6"= "#BE2102FF"))


ho = HeatmapAnnotation("Pol" = c(rep(Pol, 9)),
                       which = "col", col = cols_ho,
                       annotation_name_gp = gpar(fontsize=8,
                                                 fontface="bold"),
                       show_legend = T, gp = gpar(
                         col = "white", fontize=12), 
                       simple_anno_size = unit(0.25, "cm"),
                       show_annotation_name = T)

```


- Ploting heatmap
```{r, warning=FALSE, message=FALSE}
heats<-ComplexHeatmap::Heatmap(
  merge_data,
  col = my_palette,
   row_dend_width = unit(0.4, "cm"),
  #width = ncol(merge_data)*unit(1.21, "mm"), 
   # height = nrow(merge_data)*unit(2.4, "mm"),
  heatmap_legend_param = list(direction = "vertical",
                          title = "Relative abund(%)",
                             grid_height = unit(0.2, "cm"),
                              legend_height = unit(1, "cm"),
                              labels_gp = gpar(fontsize = 7),
                              title_gp = gpar(fontsize = 6, 
                                              fontface="bold"),
                              at = c(0,1, 10,  50, 100), break_dist = 1),
  rect_gp = gpar(col = "white"), 
  cluster_columns = F, cluster_rows = T,
  show_heatmap_legend = TRUE, top_annotation = c(ha, ho),
  #right_annotation = c(annguild, anntro),
  column_order = sort(colnames(merge_data)),
  column_split = split, column_title = NULL,
show_column_names = F,
row_names_gp = gpar(fontsize=7.5, fontface="italic"),
column_title_gp = gpar(
  fill = c("#800000" ,"#808000" ,"#008000", "#D35400", "#2E4053" )))

heats


heatm<-grid.grabExpr(draw(heats))
                     
heatm
ggsave('heat.png', width =10, height = 7, dpi = 300, plot =heatm)




```

